In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

NumPy - Numerical Python

Advantages of Numpy Arrays:

Allows several Mathematical Operations
Faster operations

In [2]:

import numpy as np

List vs Numpy - Time Taken

In [3]:

from time import process_time

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0009392500000000581


In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.0006702309999999656


In [6]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)
     

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [13]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)
     

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of a particular value
z = np.full((5,4),5)
print(z)
     

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.6769491  0.20130523 0.49323599 0.19131178]
 [0.24694393 0.58622752 0.95398173 0.79788727]
 [0.57219068 0.52613197 0.68398464 0.02878265]]


In [18]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)
     

[[96 57 77 92 88]
 [42 91 14 50 77]
 [69 66 71 84 85]]


In [19]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [20]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [21]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)
     

[10 20 20 20 50]


numpy.ndarray

In [22]:
c = np.random.randint(10,90,(5,5))
print(c)
     

[[64 41 74 75 11]
 [29 44 69 63 40]
 [25 44 67 22 41]
 [18 67 78 61 40]
 [10 59 44 26 64]]


In [23]:
# array dimension
print(c.shape)

(5, 5)


In [24]:
# number of dimensions
print(c.ndim)
     

2


In [25]:
# number of elements in an array
print(c.size)
     

25


In [26]:
# checking the data type of the values in the array
print(c.dtype)
     

int64


Mathematical operations on a np array

In [27]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list
     

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [29]:
print(a)
print(b)

[[3 1 1]
 [6 1 1]
 [4 2 2]]
[[12 16 15]
 [14 18 14]
 [10 10 11]]


In [30]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
     

[[15 17 16]
 [20 19 15]
 [14 12 13]]
[[ -9 -15 -14]
 [ -8 -17 -13]
 [ -6  -8  -9]]
[[36 16 15]
 [84 18 14]
 [40 20 22]]
[[0.25       0.0625     0.06666667]
 [0.42857143 0.05555556 0.07142857]
 [0.4        0.2        0.18181818]]


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
     

In [32]:
print(a)
print(b)

[[8 8 5]
 [6 8 8]
 [1 4 3]]
[[19 19 18]
 [12 19 15]
 [13 19 18]]


In [33]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
     

[[27 27 23]
 [18 27 23]
 [14 23 21]]
[[-11 -11 -13]
 [ -6 -11  -7]
 [-12 -15 -15]]
[[152 152  90]
 [ 72 152 120]
 [ 13  76  54]]
[[0.42105263 0.42105263 0.27777778]
 [0.5        0.42105263 0.53333333]
 [0.07692308 0.21052632 0.16666667]]


Array Manipulation

In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 5 8]
 [7 9 8]]
(2, 3)


In [35]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 7]
 [5 9]
 [8 8]]
(3, 2)


In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
     

[[5 9 2]
 [8 0 8]]
(2, 3)


In [37]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 8]
 [9 0]
 [2 8]]
(3, 2)


In [38]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[1 5 0]
 [7 9 1]]
(2, 3)


In [39]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 5]
 [0 7]
 [9 1]]
(3, 2)
